<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="3" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7714" started-at="2020-03-26T22:05:42 EDT" finished-at="2020-03-26T22:05:49 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7714" started-at="2020-03-26T22:05:42 EDT" finished-at="2020-03-26T22:05:49 EDT">
      <class name="io.duotech.tests.LoginTest">
        <test-method status="PASS" signature="setUpSuite()[pri:0, instance:io.duotech.tests.LoginTest@2473b9ce]" name="setUpSuite" is-config="true" duration-ms="140" started-at="2020-03-26T22:05:42 EDT" finished-at="2020-03-26T22:05:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:io.duotech.tests.LoginTest@2473b9ce]" name="setUp" is-config="true" duration-ms="6177" started-at="2020-03-26T22:05:42 EDT" finished-at="2020-03-26T22:05:48 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginFailingTest()[pri:0, instance:io.duotech.tests.LoginTest@2473b9ce]" name="loginFailingTest" duration-ms="432" started-at="2020-03-26T22:05:48 EDT" finished-at="2020-03-26T22:05:48 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Web Orders] but found [Web Orders Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Web Orders] but found [Web Orders Login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at io.duotech.tests.LoginTest.loginFailingTest(LoginTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFailingTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.duotech.tests.LoginTest@2473b9ce]" name="tearDown" is-config="true" duration-ms="1033" started-at="2020-03-26T22:05:48 EDT" finished-at="2020-03-26T22:05:49 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginFailingTest status=FAILURE method=LoginTest.loginFailingTest()[pri:0, instance:io.duotech.tests.LoginTest@2473b9ce] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDownSuite()[pri:0, instance:io.duotech.tests.LoginTest@2473b9ce]" name="tearDownSuite" is-config="true" duration-ms="307" started-at="2020-03-26T22:05:49 EDT" finished-at="2020-03-26T22:05:50 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- io.duotech.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
